import neton.core.Neton
import neton.core.generated.GeneratedInitializer
import neton.http.http
import neton.routing.routing

fun main(args: Array<String>) {
    Neton.run(args) {
        http {
            port = 8080
        }
        routing { }
        // Routes for every @Controller in this application, generated by KSP.
        modules(GeneratedInitializer)
    }
}
